# Generated by Django 5.1.2 on 2024-10-28 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='prizes/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Prize',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Referral',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('source_image', models.ImageField(null=True, upload_to='task_images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('score', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Task',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(null=True, upload_to='avatars/')),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='ReferredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_score', models.IntegerField(default=10)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_users', to='richSnake_app.referral')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='richSnake_app.user')),
            ],
            options={
                'verbose_name_plural': 'ReferredUsers',
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='richSnake_app.user'),
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_users', to='richSnake_app.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='richSnake_app.user')),
            ],
            options={
                'verbose_name_plural': 'UserTask',
                'unique_together': {('user', 'task')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='completed_tasks',
            field=models.ManyToManyField(related_name='completed_by', through='richSnake_app.UserTask', to='richSnake_app.task'),
        ),
    ]
