# Generated by Django 5.1.2 on 2024-11-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richSnake_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('coin', 'Coin'), ('dollar', 'Dollar')], default='coin', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='record',
            field=models.IntegerField(default=0),
        ),
    ]
