# Generated by Django 5.1.2 on 2024-10-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richSnake_app', '0002_alter_user_managers_user_date_joined_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
